version: '3.8'
services:
  db:
    image: postgres:15
    container_name: ams-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ams_user
      POSTGRES_PASSWORD: ams_password
      POSTGRES_DB: ams_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 